import attr
from collections import defaultdict

TEST_INPUT = """sesenwnenenewseeswwswswwnenewsewsw
neeenesenwnwwswnenewnwwsewnenwseswesw
seswneswswsenwwnwse
nwnwneseeswswnenewneswwnewseswneseene
swweswneswnenwsewnwneneseenw
eesenwseswswnenwswnwnwsewwnwsene
sewnenenenesenwsewnenwwwse
wenwwweseeeweswwwnwwe
wsweesenenewnwwnwsenewsenwwsesesenwne
neeswseenwwswnwswswnw
nenwswwsewswnenenewsenwsenwnesesenew
enewnwewneswsewnwswenweswnenwsenwsw
sweneswneswneneenwnewenewwneswswnese
swwesenesewenwneswnwwneseswwne
enesenwswwswneneswsenwnewswseenwsese
wnwnesenesenenwwnenwsewesewsesesew
nenewswnwewswnenesenwnesewesw
eneswnwswnwsenenwnwnwwseeswneewsenese
neswnwewnwnwseenwseesewsenwsweewe
wseweeenwnesenwwwswnew"""

PUZZLE_INPUT = """sweswseeeseseneeeeeeenwnweswe
neswswsenwseeswsesesenwseseeseseseseswnw
swswswnwwneeseneswseseneeswswseswswsenw
eeswwnwnwwnwnwnwwnwswnwnwnwnweswnw
sewwwnwwewswewswnewnwwnenesw
swswswwnesesweeswewwnewnewswswsw
nwswswnweneswswwwswswswswseswswwswsesw
nweneweneswswsenwseswnwwsesewnwwe
senwewseneswwswwsesesesenwseseesenee
sesenwseseseneseeseswswswweesewwse
swswsewswwneswseswneseswswseswswneswswsw
swswnwwwswswnwswsweswswswswswnweswsese
swnenwneeeneneswswnenewneswnwnenwneene
swseswswswseneeseswswswwswwsesw
swnwneenewweeenwenenenesenesenene
seseeweeeweeseeeneeeweee
enweseseseswseswsesesesesenewsenwsesese
neseswsweswswseswswswwswswnwsw
neneeswneswnenwneneneeewneswneenee
nenwwnenwseneenenwnenwenwswneneswnenwenw
seseseseseswseneswsesesese
seeseewnwewwnwwswnwswnweeweww
sweseseseswswseswsewsesesenwsene
sesenwwesweseseeseseeneseneeesewse
nwneneseswnenenenwne
nweeeswenweeeswwenweswwneeese
nwseswnesenwswswsewseswsenweneseeswswe
swseswswneewwnwweswwsenwwwwsww
seeseeweeeesweseneeeeenwsesw
swswswsweswswnwswsw
wwswswnwwswswwnwswneseseneseswnweesw
nenenwnwnweswnenwwneswneseswnwswnwnee
swswswswswswsweswswswswsww
sesesesenwsewenwsesewsesesenesese
seeneeeweswnenenwnwseeneseenwesw
wnenwnwwsweneswsewsesenenenewswnwnw
enwseswwnwseswswnewnwseseeseneswesew
neneneneenenewneenenenenewne
sesewewnweeeeeswe
wwewswwwwwewwww
wnesesesenewsenewsee
seseseenwseweseswsesesesesesenewnwse
swnesesewseswseswswswseswnwswsweswwsw
wwneswswseseswwneswnewswswswewswsww
swsewewnwnwswwesw
neeeenweneseneneeene
seseswnwwsewswwesesenwseswneeneenwnw
eesweeeseneenwneneenewewnwsenw
seseenwnwswswswswswneswseseswwsesenwsw
eeneseeeseeseseseneseesewwswsese
eeseseeswewnwenw
wwwwswseswwwwswswnw
swswneseswswwswswneswsewseswwswseswswswne
eeneeneneeneeeswe
wsesesewseseeesenweneseeswsesenese
nenwenenenenewnenweenesesesenewnenee
eseneeewenweeseweeswneeseneenenw
wswwwwswwwwne
nenwseseswswwsesesesesenwseeseswswsese
nenwsenwnenwnwwnwnwnwnwsenenwnenesenwnw
wseweneeswnwnwsweewswsesesesesese
seseseseswsweswseswseswswswnwnwsese
nwwswenwenenwswnene
neweeweeeeeneeseeeeeswee
nenewneweneneneneneneeeneswnenesenesw
nesewnwwneswnwswneseneseenesweeswe
nwseseneswsewseneswswewnenwseew
swswnwwwwswswswwneseswwswewneww
neeneeneseneesweeneweneenee
seseswswswswswsesesesesenwsee
wnewwwswwnwseneswsenewwewseew
nenesewwnenewnenwsenwnenenwewsenwnenenw
sesewnwnwwneswnwnewnwnwsenewww
neeswsewnwnewwwsenwesew
eeeeseeseeneweeseeewwnesenw
swwswswwwswwnesene
nenenenewwswnweeweswneneneneswnese
neneewenenenenenenenenene
swnwewnwewnwwnenwwnwwswnww
swenwwswneseswswswswswswwneewswswse
seeseeeesewseeee
wswwswseswwswwswwswnenwnesenwenwsew
wwwwwwnwwwesenewwwwewwnwsw
eeeeenenweese
nweeweeeneseneesweneswseswnwneee
wsenenenwseenwnenewseswnwnesene
wwsewwwenwweswnwwwnwwwswwnwne
nwsewnenenenenenenwsenwneswneenenenenenw
ewneswneneswenwwewneneewneseene
swswwswswswnweswswswenwswseswswswwsw
senweseseeswnenwsweweseesewse
wswwnenwewwwwwnesewnwnwsewww
nenwnenewseneneneneneneneseneeneswwnenene
neswseswswswwnwswswwwneneswseswswsesw
eneenenwneneneneneeeswnenene
neseseswsesesesesesesewe
eewnwenwseenenesenenwse
swswswewwswswswswwnwsww
wnenwsenwewnwnwnenwnwweeseswnwnwnesw
wwwenwnwswseswswswseseenewnewswswww
nwseneneeenewnenenenenenenewnenenese
eeswseswswseswnwseseseswsww
eneneenwneneeswnewnwsenwnwneswnenwnwne
swweswswswswwswsweswswswnwnesewswswne
nenwneenwwneneswnwne
nenewwsewwwsesewewswnwnwwsewww
wnwsesesesewwwswweswnwnwwnwnwsww
eseeswseeeeneseeswseswnwseseenwnwse
senwsewseseswseswneneseseseseseswswsesw
nenwneswnenwnenenwnenenwsenenwsewnenewne
sweseeneewewnesesesweweseeenee
wwnesenwnwwwnwswnwnwsenenwsewwenw
swwsewswwnewwwswswswswnwneswnewswse
wnwenwswnenenwnwnwseneswnwenwswnwsenesw
swseswseseseesewsesesesesese
wnwseseeseseswesewsenesesesesesesesesw
swswnwwnwswsenwneseseseeswsenwswwswne
swenwwseeneneweweseswneeeseenenw
swseswswneswswneewseswwswnwwseeseswsw
nwnwsenwsenwsenewnwnwwwnwnewwnwswnw
wswswwwnwwwwwwwwsewnwnewwe
nesenenenenwnwnwnwnwnenesenwnewnwnewsw
wneewwenwnwenesewsweswsweswsenw
neswswwswseeswwnwswwnwseswnenweneesese
eweneeneweseeeeeese
seseseenweseseseseese
esewneeswseswsenwneenwenwswwnenenw
eneseswnewneneenwnweesweswneneesw
nwnwnwnwwewswswewwnwwewnwnwwsw
wwwwsewwwwwnewwwnw
nwneneneneseneenewsewwsweweeseene
eeewsewwwneswwnwneseweswswwwww
nenenenenesewseneeneeneswnwnenwnenene
senesenwnwsenwsenwnwenwwnwnwnewwnwnw
swwseesesesesesenwseseeeseseseenwse
wwneeswsesenenesenewwneseenenenew
nwnwnenwnenewswnwswswneneeenwnwnwenwne
neneeneeewewneneeeeewneneneswne
nenwnewwnwneseenwswnwnwnwswnenenwnwne
enwswsweenenenwwwseneeeneweesw
wwnwwweswwwwnwewwwwwsenwnew
nwneneswsenwswnwnenwnwnenwsenwsenwnwenenw
weswnesenweseesenwse
eweeeenenwweeswsweneeenwe
wewwnewwwwwwwwwswwwwese
nwwneenwnwnwnwesewnwnwwenwnesw
swwnewswwwwseenewwwwswwwww
eswnenesesenwesesewswwseseneeesee
weneneneseswnwswneneneswnenwneeneenenee
wnwnwnenwneenwnenenenene
swswswswnwswswswewseswswseswsweeewnw
nwnwesesenwseswseeseseneswseee
swswswsesesewseesesesese
seswneswneesenwnwneswesesww
nwwswswwwswwwsewwnwewsw
swnwswswwswewnwswwnweswneswswwwswse
newesesenesesesesesenwswsesewsesesesenw
wswnwswswenwswswwwswswswse
swswswneswswsesewsese
swsewswwnenewwwswneswnwswenwnwne
eseswnwnwenwswesesweewwnwenwsesese
wwnwnwweswsewwwnwnwnwwne
swswsenwswswenwswwnewwsew
seeenwwnwwnwwnwweswwnwnwnenwnwnw
eeneswseneneneeweeew
enenwsenenwnenwnenwswnwnwwnwnweswnwnwnw
enwneeeneeeswnwneeneneneseene
wnwewwswseswnwwnwswneseeweewsw
eneneeswswneeewnwnweeeseeneee
newnwnwenwnwnwnwnwnenwnesenenwne
wswwewswswswswwswsw
swnwnwnewwswwwsenewwnwewnwwsewnw
nweeeeenwnweeeewseenwswseesew
swesenwswswwnweeneeseeeeeeesee
nenenenwnwwnwnenesenwnenwnenenwwe
eeeneeneweseeeeeswnewnweeswe
nesewwwweswswwwswnenwwwwwesww
nesweesweenweneeeswnweneeeeesw
seswseeeweseesenweneweneeswnesw
sesweswswswwseneeswnwwwsenwswnwwswsw
neneneenwnewnwseesewseneneeeeseew
seeswsesenwnwseseeseseseesenweenewse
ewswwseseswswswsene
nwnwnwnwwwsenwnwnwsewwnwnwnwsenenwnw
nwenweseenwwnwnewsweswnwwseswwnwne
wswswseswneswnwwneswnewwwsewswsw
neseswsewswswswsenenwsesesweswsweseswsw
nenwsewnwwnenwnenesesenwneswwnesenwwne
swwweswswwwnewwwwnwswwwwesw
nesenewsenwnweneewswnwwswwsenwseseswne
swwnewwwwnwwneswwsewwswwsesew
neneneneeseneewswneneseewneswnewsw
nwnenenwnenwswnwnwnwswswnwnenwnwwsesee
swwseswswswswwswnesw
enenwneeeweseseeseeswsewsewneew
wwwnwnwwwwnwwseenenenwwswwwsew
swseswsenwswswswswnwswswswnwneeswsesese
nwnenwsenwswenwnenwnwswnwnwnwnwseswnewnw
swwwwnewswnesewwnesewswwwseew
ewnwnenwnwnwnwnwnwnw
seneneswwnewnwnwsewnwnwnwseenwwwsee
seeseseenwseseenwseesenwesesenwswsese
enewnwewseswnesewwwwnwswnwnwwne
swswwswneswsweswnw
nenenewswneswenenwswneeeseewneneee
nwwewnwwnenenwnwnwsewnenwswsenwnwsw
nwwnwnenenwwsewenwswswnweswswsewnwe
nwnwswnwnwnwnwnwnwenwwseswwwwnenwwnwe
nwnesenweesewenwweseeseeeswwsw
wnewwwnwnwwwwsewwewsewwnewse
newseneenweseswesweeesweeesew
enwswneeesweswsenwseneseeseswnewse
eeseswwseneseseeeswnweeneseesee
sewswswwsesweswnwesenwnwswswsweswsw
nesenenenesenwnenwneeweneneeswneee
nwnweewnwnwnwnwnwnwnwnwnesewnwnwswnw
nwenwswswnwnenwnwnwwsenwnwnwnwenwnwnwse
seswswswswwsweswnewsweseseswnw
swseswwsesesenesesweswseseswnwwswsesw
wnweeeseseeeeenwneeweeseeee
eenwswnwwnwweenwwneswnweswwnwsw
wnewswewwswsenwsenwwwsewswnwwenew
swswneeneneneenenwnenenenesenenenwnene
newnwneneesenewswsewnwneseneeswsew
wnwewseseswwenwnenwwnwwswswwwnwnwe
enwnenenewneneneneneneneneneswswwnese
nenwswseseseswswesenwseswsene
nwnenwnwnwwneseneenenenesweeseneeswnese
nwnwswnenenwnwnwnenwnwnwnwnwnw
swswnwswswswswseswswneesenwswsweswwswesw
nwswnesewseseneneseswsesesewswneswsesw
nwnenwesenenesenwnwnenewnwwnwnwnwnwwnw
seeneneneneneenwnee
newsweeseesesesewnesesenwsesenesesese
eenewnwswnwesewnwwswnwswnwwswnwnwe
wewsewwwwsewnwnwnewwsewwswnw
swnewnwwnwswwwswwwwswewwseswwne
nwswnenwsewnwseswwwneweweeswwww
wnwnwenwnwsenwnwsewnewnwwnwnwnwenwnenw
swnesenwenwneswswneswsesewseseeseesene
nwnwnwnwewsenwswnwenwnwwenwnenw
ewneewseenwswneswenwsenwewwe
senwesenenwsewseseseseseseseswesesenw
nesenewwnweneneneneneneesenewnwneswne
neneeeswwneeeswswenenwwnewwee
weseeseseeneeeneesw
nwnwnwnenwswsenwneswenwnwsewnwneneswnenenw
wneweenwenesweneeweenenenewse
sweenwswnweneneseneeseseweswseseese
swnwnesewwwseewnewwwwwwwww
eenenenweswwnwwnw
swswnwsweswneneeswswswswswswswsenwnewse
wnenwewwewseewswswnwnesenwnwnwene
seswseseswnwseseswseswswsw
nwnwnwnwswwenwwnwwwswewwewnwnw
nesewsewneswwwsenewsenewnwwsw
nweneeeewneseseweneswseseswnesewse
wswswwwwsenenenewwswsewwwnw
eenwwwswnwwwwnwenwwewnwswswwnw
swsenwnwsesenwseswseseseneswseneswwese
sewseseseswseeneseseswsesewsesenewse
swswswswswswswswswswwswseneneeswwswsw
nenenenwneneeseeseneenewnenewneewsw
nwsenwnwnenenewnwswnwnwswnwwnwnwswnwwe
wwwnenwsenwnwnenwsewwnwsenenw
neeswwweseseenwsenwseseesesenwwne
esesewseseneneeseseenwseswswseeeee
neneneneswseneneweneswnenenw
nweswswwseswwseeneseseseswewswswswnw
swswwwnwswnewwnewwwwwwswwswe
enwwnwwnwwwnwwnwenw
sewwnwnwwewswwwswswnwwseswswswsw
swswseswnwnwswseswnwsenwswwswwswswesww
weewwwsewwnewsewnewnwwwww
nweswsenwswneseewnenwswwewnwnwnwnwenw
eeewnweeneseswsweswseenenweeswe
swswswwwswnenwsweswseswswnewneswswsw
swneswswseswsenwseswnewsesenesenwswsesw
nesewnesweswnenew
nenwsesenenenwweenesweseswneneneew
eeswnweneswseesenwwese
esewwseswnwneeseswnwswnwesenwnwnwnww
nwnwwnwwwwwnwewnwnw
nwnwwesweenenenwnweswnwwnwenesweswne
nwwswesewnwwenwswewneseseeesesenw
swwseenwnwsewsewseneneww
neswneswenwwneneneenwnwnenesewne
neeneenweweeneneseseswnwsweeee
wswnwswwswswnenwswswwwswesewswnese
nwwnwwsewnweswsesesweenenwswnwnee
sweeneneneneneneswnweneneswnesenwwnee
eeswnwsweenenesenenwwnwneswseneese
swwnwnwswseeseswswseseseswneneswsewsesene
swnwwseneswnenenenewsenewneneneenenesw
sewwseseseseseneewseeseenwseenenesee
eeenwwweneneeeeswnesweeeenwne
seseseeeneseseseswe
nwnenwsewnwsenwnwnwnwwnw
nwswnenwswneseneswnwnwesenwnenewnenene
swseswnenwseeseswsewswswsewseneseswnwse
wswwswnwnewseweneswenwswswswswnese
wsenwnwnwnwnweewnwnwnwnwseswe
eenewneseeeneeeseenwnenewneneeswe
neswnwnwswnwswenenwnewnenenenenenwenene
sewsewsesenwesesweseswswsewseneew
swwswseswneeweswswseswnwwewnwswwne
eenesweeeeenenwnwseswsesewnwsesw
wwwnwsewnwwnwsenwnwwewwwnewenwe
nwwnwneneswnwnwnwnwnwwswnenwwnwsenesesenw
swseewseseseseseneseswsesesenese
newnwsenwnwswswenwnenwnwsewswnwnwnwwnw
eeneeweeneeeseeewenweswesw
wesewwswnweseneseneweswwwwneww
wnenesenwnwneseneenwese
nenenenwnewswnenwnwswneseswswneswnwseesw
swswseswswnwseswswswswnesese
seswswnwseseseswswseseswseswsw
neswsesewnwswwnweneseseswenwnwswe
nwsesweswnesewnwswsenenenwswneseswswswsw
swnwneneneswswnenenwwsenwnwnwse
swswseseseneswneswsesesenwseneneswwsese
nenwenenwnwsenwneewnwswenenwwnenew
eewnwseeneeeeweesewseneswee
seswseswsenwseseesenwsewseeseseseee
senwwnwnwnwnenwnwwwnww
wneeswnwswseswswnwwewsw
nwsweneswneeeneenesenwneneeswnw
esweenwnenenwweneneneseneeneneeesw
seeewseeseseeseenwwseesesweese
swswsewswseeswnwnweswwswnenwswswswwsw
swnwneneneeneenenenewenenene
nwsenwnwwsenwsenenenwenwwneneswseneew
enwneswswnesenewswwe
sesesenwnwswsesenewsesenwenwseseseseswe
nwseneswneswnwneneeneeswnenenwnenwese
seenesesenwnwwswnewswwwnwwwneswne
swseswnwnwswswswswswswseswswswswneswenwsw
senwnweenwesweseeeeeeeeewese
swwseneswwswwnewwneeseswenesewsene
eseneweenenenenenwneenenwneneswneneswne
nwnesenwseeeneeesewnwweswweesw
neseseseseseewwsesee
swnwseswswswneeswswswswswswwswnwneswsw
wnwwnwsenenesesewnenwswneesw"""

@attr.s(frozen=True)
class Coord(object):
    x = attr.ib()
    y = attr.ib()

EAST_DELTA = Coord(y=0, x=1)
SOUTH_EAST_DELTA = Coord(y=-1, x=0.5)
NORTH_EAST_DELTA = Coord(y=1, x=0.5)

WEST_DELTA = Coord(y=0, x=-1)
SOUTH_WEST_DELTA = Coord(y=-1, x=-0.5)
NORTH_WEST_DELTA = Coord(y=1, x=-0.5)

DELTAS = {
    "e": EAST_DELTA,
    "w": WEST_DELTA,
    "se": SOUTH_EAST_DELTA,
    "sw": SOUTH_WEST_DELTA,
    "ne": NORTH_EAST_DELTA,
    "nw": NORTH_WEST_DELTA,
}

def solve(instructions):
    black_tiles = set()

    for instruction in instructions.split("\n"):
        destination_tile = follow(instruction)

        destination_to_tuple = (destination_tile.x, destination_tile.y)

        if destination_to_tuple in black_tiles:
            black_tiles.remove(destination_to_tuple)
        else:
            black_tiles.add(destination_to_tuple)

    return len(simulate(black_tiles))


def simulate(black_tiles):
    for i in range(100):
        black_tiles = next_state(black_tiles)

    return black_tiles


def next_state(black_tiles):

    next_black_tiles = set()

    white_tile_neighbours = defaultdict(set)

    for black_tile in black_tiles:
        x, y = black_tile
        neighbours = {
            follow(instruction, pos=Coord(x=x, y=y))
            for instruction in DELTAS
        }
        black_neighbour_count = 0
        for neighbour_coord in neighbours:
            neighbour = (neighbour_coord.x, neighbour_coord.y)
            if neighbour in black_tiles:
                black_neighbour_count += 1
            else:
                white_tile_neighbours[neighbour].add(black_tile)

        if black_neighbour_count == 1 or black_neighbour_count == 2:
            next_black_tiles.add(black_tile)

    for white_tile, black_neighbours in white_tile_neighbours.items():
        if len(black_neighbours) == 2:
            next_black_tiles.add(white_tile)

    return next_black_tiles

def follow(instruction, pos=None):
    if pos is None:
        pos = Coord(0, 0)

    i = 0
    while i < len(instruction):
        next_dir = instruction[i]
        if next_dir == "s" or next_dir == "n":
            next_dir += instruction[i+1]
            i += 1
        coord_delta = DELTAS[next_dir]


        pos = attr.evolve(
            pos,
            x=pos.x + coord_delta.x,
            y=pos.y + coord_delta.y,
        )

        i += 1

    return pos

if __name__ == "__main__":
    assert solve(TEST_INPUT) == 2208
    print(solve(PUZZLE_INPUT))
